import Head from "next/head";
import { VFC } from "react";

export const Index: VFC = () => {
  return (
    <div className="text-5xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-xl">text</div>
    </div>
  );
};
